"""
CPU tests for slurm/coco_rle.py — the pure-numpy COCO compressed-RLE decoder (todo 6j).

Standalone, no cluster data, no GPU: `myenv/bin/python tests/test_coco_rle.py`.

**Why the fixture exists.** A decoder tested against its own encoder round-trips whatever bug they
share — and the two easiest bugs here (the delta starting at the wrong run, column- vs row-major)
are both invisible to a round trip. `tests/data/coco_rle_fixture.json` was therefore generated by
**`pycocotools` itself** under the reference env (`/cluster/home/niacobone/MaskDINO/myenv`), which
is the canonical C implementation, and carries the mask bits alongside every `counts` string. The
test needs no pycocotools; only regenerating the fixture does.

The second half checks the compositing rule the RE10K build depends on: SAM2 masklets overlap, our
instance-map format is one id per pixel, and the rule is **smaller area wins** so a wall blob
cannot swallow the objects in front of it.
"""

import base64
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from slurm.coco_rle import (  # noqa: E402
    decode_counts,
    encode_counts,
    masklets_to_instance_map,
    rle_area,
    rle_on_indices,
    rle_to_mask,
)

FIXTURE = Path(__file__).resolve().parent / "data" / "coco_rle_fixture.json"
PASSED = []


def check(condition, message):
    if not condition:
        raise AssertionError(message)
    PASSED.append(message)


def load_cases():
    cases = json.loads(FIXTURE.read_text())["cases"]
    return {c["name"]: c for c in cases}


def unpack(case):
    h, w = case["size"]
    bits = np.unpackbits(np.frombuffer(base64.b64decode(case["mask_packbits_b64"]), dtype=np.uint8))
    return bits[: h * w].reshape(h, w).astype(bool)


def test_against_pycocotools():
    """Every fixture case must decode bit-for-bit to the mask pycocotools encoded."""
    cases = load_cases()
    check(len(cases) >= 8, f"the fixture carries the cases the build needs, got {len(cases)}")
    for name, case in cases.items():
        expected = unpack(case)
        got = rle_to_mask({"size": case["size"], "counts": case["counts"]})
        check(got.shape == expected.shape, f"{name}: shape {got.shape}")
        check(np.array_equal(got, expected),
              f"{name}: decodes bit-for-bit to pycocotools' mask ({case['size']})")
        runs = decode_counts(case["counts"])
        check(rle_area(runs) == case["area"],
              f"{name}: area {rle_area(runs)} matches pycocotools' {case['area']}")


def test_column_major_is_load_bearing():
    """A row-major reader would pass every square case, so use a case where h != w."""
    case = load_cases()["small_square"]                 # 7x5, a 3x3 block at rows 2:5, cols 1:4
    got = rle_to_mask({"size": case["size"], "counts": case["counts"]})
    check(got.shape == (7, 5) and got[2:5, 1:4].all() and got.sum() == 9,
          "a non-square mask lands in the right orientation (column-major, as COCO writes it)")
    runs = decode_counts(case["counts"])
    flat = np.zeros(7 * 5, dtype=bool)
    flat[rle_on_indices(runs)] = True
    check(not np.array_equal(flat.reshape((7, 5)), got),
          "reading the same runs row-major gives a DIFFERENT mask — the orientation is tested")


def test_delta_starts_at_the_third_run():
    """`x += cnts[m-2]` from m>2. Off by one and every real mask decodes to the wrong lengths."""
    runs = [4, 9, 2, 30, 1, 7]
    check(decode_counts(encode_counts(runs)).tolist() == runs,
          "runs round-trip through our own encoder")
    naive = [4, 9] + [2 + 4, 30 + 9, 1 + 2, 7 + 30]     # what "delta from the first run" would give
    check(decode_counts(encode_counts(runs)).tolist() != naive,
          "the fixture-verified decoder is NOT the delta-from-run-0 variant")


def test_multibyte_and_negative_deltas():
    check(decode_counts(encode_counts([0, 100000, 1, 3])).tolist() == [0, 100000, 1, 3],
          "runs past 5 bits survive the variable-length encoding")
    check(decode_counts(encode_counts([50, 40, 1, 2, 60, 90])).tolist() == [50, 40, 1, 2, 60, 90],
          "a run SMALLER than the one two places back needs the sign bit and round-trips")


def test_on_indices_match_the_mask():
    case = load_cases()["holed"]
    runs = decode_counts(case["counts"])
    h, w = case["size"]
    flat = np.zeros(h * w, dtype=bool)
    flat[rle_on_indices(runs)] = True
    check(np.array_equal(flat.reshape((w, h)).T, unpack(case)),
          "rle_on_indices expands to exactly the foreground of the decoded mask")


def test_bad_rle_is_rejected_not_silently_wrong():
    try:
        rle_to_mask({"size": [4, 4], "counts": encode_counts([2, 3])})
    except ValueError as exc:
        check("runs sum" in str(exc), "an RLE whose runs do not cover h*w raises, never truncates")
    else:
        raise AssertionError("a short RLE was accepted")


def test_smaller_instance_wins_the_overlap():
    cases = load_cases()
    big = {"size": cases["overlap_big"]["size"], "counts": cases["overlap_big"]["counts"]}
    small = {"size": cases["overlap_small"]["size"], "counts": cases["overlap_small"]["counts"]}
    h, w = big["size"]
    for order, label in (([big, small], "big first"), ([small, big], "small first")):
        ids = [1, 2] if label == "big first" else [2, 1]
        m = masklets_to_instance_map(order, h, w, ids=ids)
        check(np.array_equal(m == 2, unpack(cases["overlap_small"])),
              f"the small instance keeps ALL its pixels regardless of list order ({label})")
        check((m == 1).sum() == h * w - unpack(cases["overlap_small"]).sum(),
              f"the big instance keeps only what the small one does not cover ({label})")


def test_instance_map_details():
    h, w = 8, 6
    a = np.zeros((h, w), dtype=bool); a[1:4, 1:4] = True
    b = np.zeros((h, w), dtype=bool); b[5:7, 2:5] = True
    rles = [{"size": [h, w], "counts": encode_counts(_runs(m))} for m in (a, b)]
    m = masklets_to_instance_map(rles, h, w)
    check(np.array_equal(m > 0, a | b), "disjoint masklets composite to their union")
    check(sorted(np.unique(m).tolist()) == [0, 1, 2], "default ids are the 1-based masklet index")
    m = masklets_to_instance_map([rles[0], None, rles[1]], h, w, ids=[7, 8, 9])
    check(sorted(np.unique(m).tolist()) == [0, 7, 9],
          "a masklet absent from a frame (None) is skipped, and ids are honoured")
    empty = {"size": [h, w], "counts": encode_counts([h * w])}
    m = masklets_to_instance_map([empty], h, w, ids=[5])
    check(m.max() == 0, "an empty masklet contributes nothing rather than an empty instance")


def _runs(mask: np.ndarray):
    """Row-major bool mask → COCO runs (column-major, background first). Test helper only."""
    flat = mask.T.ravel().astype(np.int8)
    change = np.flatnonzero(np.diff(flat)) + 1
    edges = np.concatenate([[0], change, [flat.size]])
    runs = np.diff(edges).tolist()
    return runs if flat[0] == 0 else [0] + runs


def main() -> int:
    test_against_pycocotools()
    test_column_major_is_load_bearing()
    test_delta_starts_at_the_third_run()
    test_multibyte_and_negative_deltas()
    test_on_indices_match_the_mask()
    test_bad_rle_is_rejected_not_silently_wrong()
    test_smaller_instance_wins_the_overlap()
    test_instance_map_details()
    for message in PASSED:
        print(f"  ok  {message}")
    print(f"\n{len(PASSED)} checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
