"""
COCO compressed-RLE decoding, in pure numpy — no `pycocotools` (todo 6j).

RE10K's SAM2 masklets (`processed_re10k/sam2_results/<scene>/auto_masks.json`) store every mask
as `{"size": [h, w], "counts": "<ascii>"}`, the COCO *compressed* RLE that `pycocotools` writes.
`pycocotools` is a C extension and is **not** in `myenv`; adding it to rebuild the training set
would put a compiled dependency on the critical path of a venv that scratch has already destroyed
twice (CLAUDE.md). The format is small enough to implement exactly instead:

  * `counts` is a list of alternating run lengths, **starting with a background run**, over the
    mask flattened in **column-major** (Fortran) order;
  * each run length is written as a variable-length little-endian base-32 integer: 5 payload bits
    per byte, bit 0x20 = "one more byte follows", and on the LAST byte bit 0x10 is the sign bit;
  * every run from the **third onwards** is stored as a delta against the run two places before
    it (`x += cnts[m - 2]`), which is what makes the encoding compact and is the single easiest
    thing to get wrong.

`tests/test_coco_rle.py` checks this against a fixture generated by `pycocotools` itself
(`tests/data/coco_rle_fixture.json`, built once under the reference env), so the implementation is
verified against the canonical encoder rather than against its own inverse.

Nothing here is specific to RE10K; it is the standard format.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Optional, Sequence

import numpy as np


def decode_counts(counts) -> np.ndarray:
    """The `counts` string of a COCO compressed RLE → the run lengths it encodes."""
    if isinstance(counts, (list, tuple, np.ndarray)):        # uncompressed RLE, already runs
        return np.asarray(counts, dtype=np.int64)
    if isinstance(counts, str):
        counts = counts.encode("ascii")
    out: List[int] = []
    p, n = 0, len(counts)
    while p < n:
        x, k, more = 0, 0, True
        while more:
            c = counts[p] - 48
            x |= (c & 0x1F) << (5 * k)
            more = bool(c & 0x20)
            p += 1
            k += 1
            if not more and (c & 0x10):                      # sign-extend the last byte
                x |= -1 << (5 * k)
        if len(out) > 2:                                     # the delta starts at the THIRD run
            x += out[-2]
        out.append(x)
    return np.asarray(out, dtype=np.int64)


def encode_counts(runs: Sequence[int]) -> bytes:
    """The inverse of `decode_counts` — used only by the tests, kept here so both live together."""
    out = bytearray()
    runs = [int(r) for r in runs]
    for i, run in enumerate(runs):
        x = run - runs[i - 2] if i > 2 else run
        while True:
            c = x & 0x1F
            x >>= 5
            more = not (x == 0 and not c & 0x10) and not (x == -1 and c & 0x10)
            if more:
                c |= 0x20
            out.append(c + 48)
            if not more:
                break
    return bytes(out)


def rle_area(runs: np.ndarray) -> int:
    """Foreground pixels of a decoded RLE. The runs alternate, background first."""
    return int(runs[1::2].sum())


def rle_on_indices(runs: np.ndarray) -> np.ndarray:
    """Flat **column-major** indices of the foreground pixels — the ragged-arange expansion."""
    starts = np.cumsum(runs) - runs
    on_start, on_len = starts[1::2], runs[1::2]
    keep = on_len > 0
    on_start, on_len = on_start[keep], on_len[keep]
    total = int(on_len.sum())
    if total == 0:
        return np.empty(0, dtype=np.int64)
    offsets = np.cumsum(on_len) - on_len
    return np.repeat(on_start - offsets, on_len) + np.arange(total, dtype=np.int64)


def rle_to_mask(rle: Dict) -> np.ndarray:
    """One RLE → a bool mask of shape (h, w). Column-major, like COCO."""
    h, w = int(rle["size"][0]), int(rle["size"][1])
    runs = decode_counts(rle["counts"])
    if int(runs.sum()) != h * w:
        raise ValueError(f"runs sum to {int(runs.sum())}, not {h}*{w}={h * w}")
    flat = np.zeros(h * w, dtype=bool)
    flat[rle_on_indices(runs)] = True
    return flat.reshape((w, h)).T


def masklets_to_instance_map(rles: Iterable[Optional[Dict]], height: int, width: int,
                             ids: Optional[Sequence[int]] = None) -> np.ndarray:
    """
    Composite one frame's masklets into a single-id-per-pixel int32 map, 0 = background.

    **Overlap rule: the SMALLER instance wins.** SAM2's automatic masks are not a partition — a
    floor or wall blob routinely contains the objects standing on it — so painting largest-first
    keeps the small object and loses only the part of the big blob it covers. Ties go to the
    lower masklet index. Both halves are deterministic, which is what the id table needs.

    `ids` names the value written for each masklet (default: 1-based masklet index). `None`
    entries — a masklet absent from this frame — are skipped.
    """
    entries = []
    for index, rle in enumerate(rles):
        if rle is None:
            continue
        runs = decode_counts(rle["counts"])
        if int(rle["size"][0]) != height or int(rle["size"][1]) != width:
            raise ValueError(f"masklet {index}: size {rle['size']} != ({height}, {width})")
        if int(runs.sum()) != height * width:
            raise ValueError(f"masklet {index}: runs sum to {int(runs.sum())}, not {height * width}")
        area = rle_area(runs)
        if area == 0:
            continue
        value = index + 1 if ids is None else int(ids[index])
        entries.append((area, -index, runs, value))

    flat = np.zeros(height * width, dtype=np.int32)
    for _, _, runs, value in sorted(entries, key=lambda e: (-e[0], e[1])):
        flat[rle_on_indices(runs)] = value
    return flat.reshape((width, height)).T
